language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-fast-neural-style-transfer .
  - docker run -it -d --rm -p 5000:5000 max-fast-neural-style-transfer
  - pip install -r requirements-test.txt
before_script:
  - flake8 . --max-line-length=127
  - bandit -r .
  - sleep 30
script:
  - pytest tests/test.py
